### ISSUE TITLE
Cloak of Agility bug

### ISSUE THREAD

**Issue by aetsi12** [DavidM1A2/AfraidOfTheDark#6]
Whenever I try to move this item in my inventory or to a chest the game crashes. Pity.

[21:49:40] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.DavidM1A2.afraidofthedark.common.item.ItemCloakOfAgility.func_77624_a(**ItemCloakOfAgility.java:45**)

**Comment by DavidM1A2** [comment]
Sorry you ran into this issue, it looks like a simple fix on my end. What is your cloak of agility keybind set to? The game is crashing because it cannot figure out what key it's bound to when you hover over the item. Is it set to a mouse button or some special macro key? I believe you can mitigate the issue by setting this key binding to a key found on every keyboard for now, like a letter key.

**Comment by DavidM1A2** [comment]
I managed to replicate the issue by binding "Roll with Cloak of Agility" to Left Mouse, and then looking at the item. For now avoid keybinds to mouse buttons or non-traditional keys (anything that isn't on a standard keyboard, like macro keys etc). This will be fixed next update!

**Comment by aetsi12** [comment]
Sorry about the late answer and thank you for the effort. The bug appeared when binding the cloack use to the "<" button. The bug appeared too with the wrist crossbow.

**Comment by DavidM1A2** [comment]
This was fixed in v1.1.0
