### ISSUE TITLE
Crash while signing book gui

### ISSUE THREAD

**Issue by TimeConqueror** [DavidM1A2/AfraidOfTheDark#7]
![image](https://user-images.githubusercontent.com/25156941/66067309-f8291900-e553-11e9-82f0-e6da6b3a7b88.png)
So if I try to switch keyboard to Russian Language, this book will freeze the game forever. So there is no crash-report. Logs also tell nothing.

**Comment by DavidM1A2** [comment]
I'll take a look into it. I haven't tested the mod in anything but English, but it might be an easy fix.

**Comment by DavidM1A2** [comment]
The issue is due to the font renderer I use to create custom font. It's getting stuck in an infinite loop because it doesn't know how to draw the Russian character. I will try to figure out a way to ensure it creates the correct (Based on keyboard) language characters and draw a ☐ if the letter is unrecognized.

**Comment by TimeConqueror** [comment]
What if it will draw unrecognized symbols with common font, like Calibri/Sans Serif or Minecraft font, because they support many languages.

**Comment by DavidM1A2** [comment]
Fixed in version 1.2. You'll need to enable "Use Calibri Font" in the afraidofthedark.cfg file to show Russian characters: https://www.curseforge.com/minecraft/mc-mods/afraid-of-the-dark/files/2887243
